### PR TITLE
Homework 1 Ibraheem Barbahan ITMO M41382

### PR DESCRIPTION
**Pull request by ibraheem94**

### CODE REVIEW

**Comment by danyaberezun** [comment]
pr должен содержать только *.lama файлы

**Comment by ibraheem94** [comment]
so would you like me to simply delete the other files or just a notification for the next homework?

**Comment by danyaberezun** [comment]
Надо почистить =(

**Comment by ibraheem94** [comment]
i am not able to delete some of the files (binary test files) , do you mean a new pull request? or how?

**Comment by ibraheem94** [comment]
i deleted all that i'm allowed to delete , is it acceptable now?

**Comment by danyaberezun** [comment]
accepted

**Pull request closed without merging**
